config/routes.rb
Fanfare::Application.routes.draw do

  devise_for :users

  resources :bands

  namespace :admin do
    resources :users, :only => [:index, :show, :update] do
      member do
        put :edit_points
      end
    end
    resources :products, :except => :show do
      put :toggle_visible, :on => :member
    end
    resources :product_orders, :only => [:index, :show] do
      put :toggle_sent, :on => :member
    end
    root :to => "users#index"
  end

  resources :product_orders, :only => [:new, :create] do
    member do
      get :finalize
      get :thanks
      post :thanks
    end
  end

  resources :payments, :only => :none do
    collection do
      post :paypal_ipn
    end
  end

  resources :products, :only => [:index, :show]
  resources :users, :except => [:index, :destroy]

  root 'home#index'
  get '*a', :to => 'home#error_404'

end

app/models/product_order.rb
class ProductOrder < Order

  SHIPPING_COUNTRIES = ['ES', 'PT', 'IT', 'DE']

  has_many :order_products, -> { order('created_at ASC') }, dependent: :destroy, :foreign_key => "order_id"
  has_many :products, :through => :order_products

  accepts_nested_attributes_for :order_products

  before_validation :set_price, :on => :create
  before_validation :set_bonus_points, :on => :create
  validates_inclusion_of :shipping_country, :in => SHIPPING_COUNTRIES

  ["bonus_points", "price"].each do |attr|
    define_method "calculate_#{attr}" do
      order_products.map do |order_product|
        order_product.quantity * order_product.product.send(attr)
      end.sum
    end
  end

  scope :product_order, -> (product_order_id) { where product_order_id: product_order_id }

  private

  def update_stock
    stock = true
    transaction do
      order_products.each do |order_product|
        quantity = order_product.quantity
        product = order_product.product
        product.with_lock do
          product.quantity -= quantity
          if product.quantity < 0
            stock = false
            raise ActiveRecord::Rollback
          else
            product.save!
          end
        end
      end
    end
    self.paid_at = Time.now
    self.set_no_stock! unless stock
  end

  def notify_payment
  end

  def notify_no_stock
  end

  def set_price
    self.price = calculate_price.round(2)
  end

  def set_bonus_points
    self.bonus_points = calculate_bonus_points
  end

  def calculate_ref
    [Time.now.strftime("%Y%m"), user.id, user.product_orders.count].join
  end

  def update_user_data
    user.shipping_name = shipping_name
    user.shipping_last_name = shipping_last_name
    user.shipping_address = shipping_address
    user.shipping_town = shipping_town
    user.shipping_zip = shipping_zip
    user.shipping_province = shipping_province
    user.shipping_country = shipping_country
    user.shipping_phone = shipping_phone
    user.save
  end
end

app/controllers/admin/product_orders_controller.rb
class Admin::ProductOrdersController < Admin::AdminController
  load_resource
  before_filter :initialize_countries, :only => :show

  def index
    @states = Order::STATES
    @state = params[:state] || "pending"
    @shipping_countries = Carmen::Country.all
    @shipping_country = params[:shipping_country]
    @product_orders = @product_orders.pending if params[:state].blank?
    filtering_params(params).each do |key, value|
      @product_orders = @product_orders.public_send(key, value) if value.present?
    end

    @product_orders = @product_orders.newest_first.paginate(:page => params[:page], :per_page => 10)
  end

  def toggle_sent
    @product_order.toggle!(:sent)
    redirect_to :back
  end

  private

  def initialize_countries
    @shipping_countries = Carmen::Country.all.select{|c| ProductOrder::SHIPPING_COUNTRIES.include?(c.code)}
  end

  def filtering_params(params)
    params.slice(:shipping_country, :state)
  end
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  load_resource
  before_filter :initialize_countries

  def new
    @product_order = ProductOrder.new(:user_id => current_user.id)
    @product_order.shipping_name = current_user.shipping_name
    @product_order.shipping_last_name = current_user.shipping_last_name
    @product_order.shipping_address = current_user.shipping_address
    @product_order.shipping_town = current_user.shipping_town
    @product_order.shipping_zip = current_user.shipping_zip
    @product_order.shipping_province = current_user.shipping_province
    @product_order.shipping_country = current_user.shipping_country
    @product_order.shipping_phone = current_user.shipping_phone

    @products = Product.visible
    @products.each do |product|
      @product_order.order_products.build(:product_id => product.id, :quantity => 0)
    end
  end

  def create
    if params[:product_order]
      purge_null_products(params[:product_order])
      @product_order = ProductOrder.new(product_order_params)
      @product_order.user = current_user

      if @product_order.save
        redirect_to finalize_product_order_path(@product_order)
      else
        redirect_to :back
      end
    else
      redirect_to :back
    end
  end

  def finalize
    redirect_to root_path if @product_order.paid
  end

  private

  def purge_null_products(params_order)
    params_order[:order_products_attributes] = params_order[:order_products_attributes].select do |k,v|
      v["quantity"].present? && v["quantity"].to_i > 0
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_order_params
    params.require(:product_order).permit(:user_id, :price,
    {order_products_attributes: [:id, :product_id, :quantity]},
    :shipping_name, :shipping_last_name, :shipping_address,
    :shipping_town, :shipping_zip, :shipping_province,
    :shipping_country, :shipping_phone, :bonus_points,
    :paid, :ref)
  end

  def initialize_countries
    @shipping_countries = Carmen::Country.all.select{|c| ProductOrder::SHIPPING_COUNTRIES.include?(c.code)}
  end
end

app/views/product_orders/_price_and_bonus.html.slim
#order-info.trailer
  h5#order_price
    =' "Preu:"
    b#price-value =' number_with_delimiter(@product_order.price)
    b €

  h5#order-bonus_points
    =' "Bonus:"
    b#bonus_points-value =' number_with_delimiter(@product_order.bonus_points)
    b= "punts"

app/views/product_orders/finalize.html.slim
h1 = "Completar comanda"

= render "price_and_bonus", :order => @product_order

table.table
  thead
    th
    th
    th = "Preu"
    th = "Bonus"
  - @product_order.order_products.each do |order_product|
    - product = order_product.product
    tr
      td.span3
        .center = link_to image_tag(product.product_index_image_url(:small)), product
      td.span2 = product.name
      td.span2
        =' product.price
        | €
      td.span2 = number_with_delimiter(product.bonus_points)
      td.span1 = order_product.quantity

.pay-button
  = payment_service_for @product_order.ref, APP_CONFIG["paypal"]["account"], :amount => @product_order.price, :currency => "EUR", :service => :paypal do |service|
    - service.customer :first_name => @product_order.shipping_name,
        :last_name => @product_order.shipping_last_name,
        :email => @product_order.user.email,
        :phone => @product_order.shipping_phone
    - service.shipping_address :city => @product_order.shipping_town,
        :address1 => @product_order.shipping_address,
        :state => @product_order.shipping_province.camelize,
        :country => @product_order.shipping_country,
        :zip => @product_order.shipping_zip

    - service.shipping 0
    - service.tax '0'
    - service.item_name "Fanfare"

    - service.notify_url paypal_ipn_payments_url
    - service.return_url thanks_product_order_url(@product_order)
    - service.cancel_return_url finalize_product_order_url

    = submit_tag "Pagar", :id => 'button_credit_card', :class => "strong-button"

app/views/product_orders/new.html.slim
header.title-wrapper
  h1 = t("navigation.shop")

section.profile-wrapper
  - if @products.any?
    = simple_form_for @product_order do |f|
      table.table#order-form.trailer
        thead
          th
          th
          th = t("price")
          th = t("bonus")
          th
        = f.fields_for :order_products do |order_product|
          - product = order_product.object.product
          tr
            td
              .center = link_to image_tag(product.product_index_image_url(:small)), product
            td = product.name
            td
              =' product.price
              | €
            td = number_with_delimiter(product.bonus_points)
            td = order_product.input :quantity, :label => false, :collection => (0..10), :include_blank => false, :input_html => {class: "quantity", price: product.price, bonus: product.bonus_points}
            = order_product.hidden_field :product_id, :value => order_product.object.product.id

      = render "price_and_bonus", :order => @product_order
      .columns.large-8.medium-12
        = f.input :shipping_name, :label => t(".shipping_name")
        = f.input :shipping_last_name, :label => t(".shipping_last_name")
        = f.input :shipping_address, :label => t(".shipping_address")
        = f.input :shipping_town, :label => t(".shipping_town")
        = f.input :shipping_zip, :label => t(".shipping_zip")
        = f.input :shipping_province, :label => t(".shipping_province")
        = f.input :shipping_country, :label => t(".shipping_country") do
          = f.select :shipping_country, region_options_for_select(@shipping_countries, @product_order.shipping_country), {prompt: t(".shipping_country_choice")}, :required => true
        = f.input :shipping_phone, :label => t(".shipping_phone")

        = button_tag t(".buy"), class: "btn"

- content_for :custom_js do

  javascript:
    $("select").on("change", function() {
      total_bonus = 0
      total_price = 0
      $("#order-form select").each(function(i, quantity_element){
        price = quantity_element.getAttribute("price")
        bonus = quantity_element.getAttribute("bonus")
        quantity = quantity_element.value
        total_bonus += bonus * quantity
        total_price += price * quantity
        total_price = Number((total_price).toFixed(2));
      })
      $("#price-value").text(total_price)
      $("#bonus_points-value").text(addFormatToNumber(total_bonus))
    });

app/views/product_orders/thanks.html.slim
= "Gràcies per comprar #{@product_order.ref}."