config/routes.rb
Fanfare::Application.routes.draw do

  devise_for :users

  resources :bands

  namespace :admin do
    resources :users, :only => [:index, :show, :update] do
      member do
        put :edit_points
      end
    end
    resources :products, :except => :show do
      put :toggle_visible, :on => :member
    end
    resources :product_orders, :only => [:index, :show] do
      put :toggle_sent, :on => :member
    end
    root :to => "users#index"
  end

  resources :product_orders, :only => [:new, :create] do
    member do
      get :finalize
      get :thanks
      post :thanks
    end
  end

  resources :payments, :only => :none do
    collection do
      post :paypal_ipn
    end
  end

  resources :products, :only => [:index, :show]
  resources :users, :except => [:index, :destroy]

  root 'home#index'
  get '*a', :to => 'home#error_404'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_products
  has_many :product_orders, :through => :order_products

  scope :visible, -> { where(:visible => true) }

  validates_presence_of :name, :price, :bonus_points
  validates_numericality_of :quantity, :greater_than_or_equal_to => 0

  mount_uploader :product_index_image, ProductImageUploader
  mount_uploader :product_show_image, ProductShowImageUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:update, :edit, :destroy, :toggle_visible]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product created."
    else
      flash[:error] = "It was not possible to create the product."
    end

    redirect_to admin_products_path
  end

  def update
    if @product.update_attributes(product_params)
      flash[:notice] = "Product updated."
    else
      flash[:error] = "It was not possible to update the product."
    end
    redirect_to admin_products_path
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Product removed."
    else
      flash[:error] = "It was not possible to remove the product."
    end

    redirect_to admin_products_path
  end

  def toggle_visible
    @product.toggle!(:visible)
    redirect_to :back
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :bonus_points, :quantity, :product_index_image,
    :product_show_image, :description, :visible)
  end
end

app/controllers/products_controller.rb
# encoding: utf-8
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.visible
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.visible.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :bonus_points, :product_index_image,
    :product_show_image, :description, :visible)
    end
end

app/views/admin/products/edit.html.slim
= simple_form_for [:admin, @product] do |f|
  = f.input :name
  = f.input :price
  = f.input :bonus_points
  = f.input :quantity
  = f.input :visible, boolean_style: :nested
  = f.input :product_index_image
  = f.input :product_show_image
  = f.input :description
  = f.submit

app/views/admin/products/index.html.slim
h1 Productes
br
= link_to "Nou producte", new_admin_product_path, :class => "btn btn-primary"

table.table.table-striped
  thead
    tr
      th Producte
      th Preu
      th Bonus
      th Quantitat
      th Visible
      th
  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.price
        td = product.bonus_points
        td = product.quantity
        td.span2
          - message = product.visible ? "Ocultar" : "Mostrar"
          = link_to message, toggle_visible_admin_product_path(product), :class => "btn btn-mini", :method => :put
        td =' link_to "Editar", edit_admin_product_path(product), :class => "btn btn-mini"

app/views/admin/products/new.html.slim
= simple_form_for [:admin, @product] do |f|
  = f.input :name
  = f.input :price
  = f.input :bonus_points
  = f.input :quantity
  = f.input :visible, boolean_style: :nested
  = f.input :product_index_image
  = f.input :product_show_image
  = f.input :description
  = f.submit