config/routes.rb
Fanfare::Application.routes.draw do

  devise_for :users

  resources :bands

  namespace :admin do
    resources :users, :only => [:index, :show, :update] do
      member do
        put :edit_points
      end
    end
    resources :products, :except => :show do
      put :toggle_visible, :on => :member
    end
    resources :product_orders, :only => [:index, :show] do
      put :toggle_sent, :on => :member
    end
    root :to => "users#index"
  end

  resources :product_orders, :only => [:new, :create] do
    member do
      get :finalize
      get :thanks
      post :thanks
    end
  end

  resources :payments, :only => :none do
    collection do
      post :paypal_ipn
    end
  end

  resources :products, :only => [:index, :show]
  resources :users, :except => [:index, :destroy]

  root 'home#index'
  get '*a', :to => 'home#error_404'

end

app/views/layouts/_admin_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Inici', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/admin_navigation_links'

      .visible-lg-inline-block.pull-right.text-info
        == render "shared/user_signed_in"

app/views/layouts/_admin_navigation_links.html.slim
li= link_to "Usuaris", admin_users_path
li.dropdown
  = link_to "Botiga", "#", "data-toggle" => "dropdown", :class => "dropdown-toggle"
  ul.dropdown-menu
    li= link_to "Productes", admin_products_path
    li= link_to "Comandes", admin_product_orders_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Inici', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

      .visible-lg-inline-block.pull-right.text-info
        == render "shared/user_signed_in"

app/views/layouts/_navigation_links.html.slim
li= link_to "Shop", products_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Fanfare'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Fanfare'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :custom_js

app/views/layouts/backoffice.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Fanfare'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Fanfare'}"
    == stylesheet_link_tag "backoffice", :media => 'all', 'data-turbolinks-track' => true
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    == csrf_meta_tags
  body
    header
      == render 'layouts/admin_navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag 'backoffice', 'data-turbolinks-track' => true
    = yield :custom_js

app/views/layouts/landing.html.slim
doctype html
html
  head
    / = render "shared/metas"

    link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css"

    /[if lte IE 8]
    link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css"

    '<!--[if gt IE 8]><!--> <link href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css" rel="stylesheet">  <!--<![endif]-->

    /! CSS
    = stylesheet_link_tag  :application, :media => "all"

    /! JS
    = javascript_include_tag :application

    meta name="viewport" content="width=device-width, initial-scale=1.0"

  body.landing
    /! Flash messages
    / = render "shared/flash"

    /! Show Referral user
    / = render "shared/referral"

    = yield

    / = render "shared/footer"

    / /! Cookies
    / = render "shared/cookies"
    #fb-root

    = yield :custom_js

    - if Rails.env.production?
      = render "shared/google_analytics"